name: Automated tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID: 
      ALLURE_USERNAME:

env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_ENDPOINT: https://nabdirov.testops.cloud/
  ALLURE_PROJECT_ID: 1
  ALLURE_RESULTS: allure-results
      

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://nabdirov.testops.cloud/
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 1
      - name: run all tests
        # run: echo $ALLURE_PROJECT_ID
        run: sudo npm install -g newman-reporter-allure
      - run: allurectl watch -- newman run first_ollection.postman_collection.json -r cli,allure --reporter-allure-export allure-results
        # continue-on-error: true
      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1
